spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cafe_ordering_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
